generate array complete
Dmitriy-Bukreev/canvas-lesson pull request #7
Opened 2024-01-24 19:58 UTC by nagibator300000

please give me more rc

2024-01-24 20:06 UTC, Dmitriy-Bukreev commented on utils/index.js
> +  for (let i = min; i < max; i += step) {
Почему не через map?

2024-01-24 20:07 UTC, nagibator300000 commented on utils/index.js
> +  for (let i = min; i < max; i += step) {
потому , бумер

2024-01-24 20:07 UTC, Dmitriy-Bukreev commented on utils/index.js
> +  const min = stop !== null ? start : 0;
Вот это круто!

2024-01-24 20:07 UTC, nagibator300000 commented on utils/index.js
> +  const min = stop !== null ? start : 0;
Всё круто

2024-01-26 20:29 UTC, Dmitriy-Bukreev requested changes

2024-01-26 20:29 UTC, Dmitriy-Bukreev commented on tasks/01-line-chart/chart/axis.js
> -import generateArray from '@utils';
Надо починить

2024-01-27 13:26 UTC, Dmitriy-Bukreev commented on tasks/01-line-chart/chart/axis.js
> +  static generateLabels(from, to, step) {
Забери тест из последнего коммита и протестируй функцию снова.
Она не работает, если step < 1.

2024-02-04 16:09 UTC, Dmitriy-Bukreev commented
Велл дан!

2024-02-04 16:11 UTC, merged